project_id = "frsaqmaoguadryrjgcxv"

[functions.idx-properties]
verify_jwt = false

[functions.scrape-sothebys-dubai]
verify_jwt = false

[functions.scrape-christies-dubai]
verify_jwt = false

[functions.scrape-bayut-dubai]
verify_jwt = false
